### ISSUE TITLE
change date in place edit text field display value format??

### ISSUE THREAD

**Issue by lefthandmagic** [bernat/best_in_place#110]
I'm using date in place edit with the date picker jquery ui plugin.

Here is my code

  = best_in_place_if signed_in?, @movie,:release_date , :type => :date,
   :display_as => :get_sanitized_release_date

:get_sanized_release_date returns date in the "dd MM yy" format.

Also, my date picker defaults are setup as below

```
$.datepicker.setDefaults({
  changeYear : true,
  changeMonth : true,
  yearRange: '1900:+5',
  dateFormat: 'dd MM yy'
});
```

In the page the date is displayed in the right format.

When activating best_in_place, the text box is rendered and the jquery plugin is activated.

The problem I'm facing is that the text box displays the date in the format without using the sanitized_format

For instance,
Oct 26th 2011
is displayed as
2011-10-26 00:00:00 UTC

I would like to display this as, 26 October 2011 if possible on the edit text box too.

An example is posted here
http://postimage.org/image/fia3sixnx/

Any help with this will be great. Thank you.

**Comment by myselfrajeshco** [comment]
Is there any solution for this issue so far?

**Comment by sacredceltic** [comment]
Not that I know of. That would be nice...
