### ISSUE TITLE
Problem if used with will_paginate - stops working page 2-n

### ISSUE THREAD

**Issue by BobWalsh** [bernat/best_in_place#135]
I'm using best_in_place to edit table values paginated via will_paginate. Problem is BIP in not bound to items after the will_paginate changes which items are displayed.

I thought simply rerunning the BIP js on will_paginate would work: nope.

<script type="text/javascript" charset="utf-8">
$(document).ready(function() {
    $('.pagination a').attr('data-remote', 'true').ajaxSuccess(function(){
  $('.best_in_place').best_in_place();
});
});
</script>

Any suggestions, and more usefully code example of how to deal with what must be a very common situation?

**Comment by giangnguyennet** [comment]
4 years later me too having the same problem with rails `4.2.5` and best_in_place `3.0.3`. Any solution yet please?
