### ISSUE TITLE
How to limit the best_in_place's text box size to its wrapping div

### ISSUE THREAD

**Issue by udaykadaboina** [bernat/best_in_place#175]
I have a table and when user tries to change the text of an element, due to `best_in_place` configured on it, the Text box appears which is of default size 20 char. I want to limit it to the size of the `<tr>` block itself. Because I don't want my table to **wobble** when some one clicks for text change and then it resizes that block to orginal `<tr>` elements width.

Or in other words, How to stop the **wobbling** of element sizes if we have the form as table form.

**Comment by lacco** [comment]
I experienced the same problem and was only able to solve it by using fixed column width:

```
  .bip-cell-90 {
    min-width: 90px;

    .form_in_place {
      input {
        width: 100%;
      }
    }
  }
```

```
%td.bip-cell-90= best_in_place(...)
```
