### ISSUE TITLE
Display checkbox

### ISSUE THREAD

**Issue by sevenmaxis** [bernat/best_in_place#178]
In the description the checkbox is a collection of strings. What about real checkbox element  &#x2610; and &#x2611; ?

**Comment by sanjusoftware** [comment]
if you are using font-awesome, you can achieve this as following:

```
= best_in_place req, :method, :url => your_path, as: :checkbox, collection: {false: "<i class='fa fa-square-o'></i>".html_safe, true: "<i class='fa fa-check-square-o'></i>".html_safe}
```
