### ISSUE TITLE
Using :display_with cannot find methods in application helper

### ISSUE THREAD

**Issue by ZachBeta** [bernat/best_in_place#240]
I've previously been using a method for markdown in multiple locations throughout my view, but that is not visible to ViewHelpers and I'm having significant trouble making it work out.

**Comment by jaypinho** [comment]
It looks like the best workaround for this is to use the lambda syntax with :display_with, which allows you to call these helpers.

**Comment by acrolink** [comment]
As an alternative, lambda syntax works perfectly.

**Comment by acrolink** [comment]
As an alternative, lambda syntax works perfectly.
