### ISSUE TITLE
Add support to TestHelpers for custom activators

### ISSUE THREAD

**Issue by rogercampos** [bernat/best_in_place#29]
Add an addition :activator option to bip_text and other helper methods to make them work when you use best in place with a custom activator.

**Comment by vanboom** [comment]
:+1:   I love the ability to select a custom activator, but bip_text(...) does not work when :activator is used.  

Is there a solution that lets us use bip_text with a custom activator?

**Comment by vanboom** [comment]
Fire a click on the activator before your bip_text call and it will work...
````ruby
find(:css, "#activator").click
bip_text( x, :name, "new value")
```
