### ISSUE TITLE
:nil doesn't work when best_in_place is in a partial inserted via AJAX

### ISSUE THREAD

**Issue by betjaminrichards** [bernat/best_in_place#297]
I have a list of records on my page. I submit a form remotely via AJAX and the new record is appended to the list. All best_in_place features immediately work apart from the `:nil` option. This doesn't display the default value that I set. This makes it impossible to edit the value unless the user refreshes the page. Then the value is present and the user can click.

Is this a known bug? Can anyone suggest a work around?

**Comment by matt212** [comment]
I am using partial concept in my existing codebase 
however, i am unable to initialize  "best_in_place" 
for you reference purpose

```
$('#my_dashboard_comments').on('click', function(){
    $('.best_in_place').best_in_place();
});
```

Error 
`
Uncaught Missing instance data for this datepicker`

Could you please provide any pointers in order to resolve this critical issues 
Many thanks !
