### ISSUE TITLE
Can't generate collection content from a ActiveRecord::Relation

### ISSUE THREAD

**Issue by bvogel** [bernat/best_in_place#385]
I'm using the current `master` version of best_in_place and can't figure out how to generate the collection for a select element. Previously I used something like this: 
`Object.all.map{|o| [o.id, o.name] }` - which worked fine. The new syntax requires some odd curly braced string, I tried to use `Object.all.map{|o| {o.id => o.name} }` but that just displays the hashes als options. 
What is the recommended way to populate the collection?

**Comment by kylekeesling** [comment]
Hash[ *Category.all.collect { |v| [ v.id, v.name ] }.flatten ] seems like a dirty hack to get this done. Why is my collection automatically being turned into a hash? Shouldn't we just be able to pass an array of arrays in, like Document::SystemPdfs.map{ |pdf| [pdf.class_name, pdf.description] } and accomplish the same thing?

**Comment by danielricecodes** [comment]
I don't understand why the Hash+`collect` syntax works, but it does!

Here's my unchanged code to help others who arrive here.  I am embedding Best In Place into an ActiveAdmin index table, hence the first line with the `column` block.

```ruby
column :contact_type do |resource|
  best_in_place resource, :contact_type_id,
  url: [:admins, resource],
  as: :select, 
  collection: Hash[ *ContactType.all.collect { |v| [ v.id, v.name ] }.flatten ]
end
```
