### ISSUE TITLE
Placeholder not working in rails 4.0

### ISSUE THREAD

**Issue by btazi** [bernat/best_in_place#429]
Hi I'm a rails begginer so if I say something wrong please bear with me. I have tried to make the placeholder work since yesterday but I really don't know what's wrong.
I'm using the last master branch: gem 'best_in_place', git: 'git://github.com/bernat/best_in_place.git', branch: 'master'
here's the input field in my view: <p>téléphone:  <em> <%= best_in_place @user, :telephone, type: :input, url: profile_path(@user), place_holder: "click here to edit" %> </em><br></p>
I also have tried as: :input; path: profile_path  and nil: "click here to edit", but the issue remains the same. 
I get an empty span and there's no way to edit it.

I also tried to use the activator with a button but it's not working when there is no data in the field.
I asked a question on stackoverflow as well: http://stackoverflow.com/questions/27454174/nil-value-not-showing-with-best-in-place-gem-in-rails-4-0
Any suggestion/answer would be greatly appreciated.

**Comment by vzelenko** [comment]
I think it did include the function.  But he is using CoffeeScript, which shorthands that with 

$ -> (or jQuery ->, which is the same thing)
