### ISSUE TITLE
Select type is being sorted by the collection key

### ISSUE THREAD

**Issue by andrerpbts** [bernat/best_in_place#430]
Hi,

I'm using the best_in_place, to edit values with `select` type. But, I discovered that it isn't ordering like the collection I've set.

So, after some tests, I figured out if you pass the hash in this way:

``` ruby
<%= best_in_place @user, 
                  :country, 
                  :type => :select, 
                  :collection => {"4" => "France", "3" => "Germany", "2" => "Italy", "1" => "Spain" } %>
```

You'll get the result:

```
<option value="1">Spain</option>
<option value="2">Italy</option>
<option value="3">Germany</option>
<option value="4">France</option>
```

It's all happens because the JSON's parse. It's ordering by the key number, if a hash is given, see:

``` javascript
JSON.parse('{"4":"France", "3":"Germany", "2":"Italy", "1":"Spain"}'); 
-> Object { 1: "Spain", 2: "Italy", 3: "Germany", 4: "France" }
```

So, I think the right way to build this element, is using Array, like:

``` javascript
JSON.parse('[["4","France"], ["3","Germany"], ["2","Italy"], ["1","Spain"]]'); 
```

What do you think?

**Comment by bvogel** [comment]
@seuros Can we please reopen this? I'm still seeing the ordering issue. When building with `collection: [[1, 'Spain'], [3, 'Germany'], [2, 'Italy'], [4, 'France']]` the generated select will show 'Spain', 'Italy', 'Germany', 'France'  - even using the provided code from the Readme. I'm on Rails 4.2 with ruby 2.1.5.

**Comment by seuros** [comment]
Try master please.

**Comment by bvogel** [comment]
Tried master - no dice. Aren't master and 3.0.3 identical in the relevant sections?

**Comment by bvogel** [comment]
@stereodenis may be 7e831936f019cabdbc8e875583bc1e6858095fd2 caused a regression?

**Comment by maland** [comment]
i am also using 3.0.3 and experiencing the same problem

**Comment by stereodenis** [comment]
@andrerpbts this PR should fix right order https://github.com/bernat/best_in_place/pull/459
