### ISSUE TITLE
Select box collection array of numbers syntax

### ISSUE THREAD

**Issue by reubenbrown** [bernat/best_in_place#440]
I have a select tag in my form that I am converting to use best_in_place

`= f.select :hour, (0..8).to_a`

The collection I am using is an array of static numbers. To get the same collection output in best_in_place I had to write:

     = best_in_place @day, :hour, as: :select, collection: [[0], [1], [2], [3], [4], [5], [6], [7] ,[8]]

For small number ranges this may be fine, but for larger number ranges it seems that there should be a cleaner syntax for doing this.

**Comment by seuros** [comment]
```
Array.new(9) {|x| [x]}
=> [[0], [1], [2], [3], [4], [5], [6], [7], [8]]
```
:smiley_cat:

**Comment by reubenbrown** [comment]
@seuros Haha wow totally blanked on that solution. Thanks!
