### ISSUE TITLE
FIX: For working checkboxes

### ISSUE THREAD

**Issue by samstickland** [bernat/best_in_place#442]
Hi,

I had a problem where checkboxes were issuing ajax updates when clicked but they didn't change their display. I tracked the problem down to line 126 - 129 in lib/assets/javascripts/best_in_place.js:

            case "checkbox":
                editor.element.html(this.arrayToObject(this.values)[value]);
                break;

The problem is that this.values is already an array, not an object. This slight change fixes the problem:

            case "checkbox":
                editor.element.html(this.values[value]);
                break;

**Comment by stereodenis** [comment]
@samstickland i working on this issue. I will make a PR soon

**Comment by jcmagalhaes** [comment]
:+1: 
Had the same problem and the solution provided fixed the issue

**Comment by MentalPower** [comment]
Submitted PR since it seems to work properly without any side-effects.

**Comment by seuros** [comment]
@

**Comment by stereodenis** [comment]
@jcmagalhaes What about specs?
I revert this changes in this PR https://github.com/bernat/best_in_place/pull/457
And now tests are green

**Comment by worldnamer** [comment]
@stereodenis You should reopen this issue.

After spending an evening figuring out the problem, I see now why the tests were failing for you. There is a bug in best_in_place's interpretation of the collection option. Per the documentation:

>If you are using the :select type then you must specify the collection of values it takes as a hash where values represent the display text and keys are the option's value when selected. If you are using the :checkbox type *you can specify the two values it can take*, or otherwise they will default to Yes and No.

Essentially, you can call best_in_place like this:

```
best_in_place @user, :receive_email, as: :checkbox, collection: ["No thanks", "Yes of course"]
```

If you do, then the javascript will fail. There are two tests that should be changed to reflect the documented way of using this helper: spec/integration/js_spec.rb:267 and 283 (or search for "use bip_bool to change a boolean value"). When you change these, the error will replicate.

I don't know how you want to proceed - possibly changing the documentation to use the same syntax as selects would be prudent, as that does work. It seems like a breaking change from previous versions though.

**Comment by stereodenis** [comment]
@worldnamer yep, the documented way is not reflecting in specs. I will add an array spec

**Comment by stereodenis** [comment]
@worldnamer here is my PR https://github.com/bernat/best_in_place/pull/463
