### ISSUE TITLE
display_with and as: :select don't work together?

### ISSUE THREAD

**Issue by shyrahnama** [bernat/best_in_place#448]
Hi there,

I'm trying to use display_with to show a default value if a field isn't set and it's not working at all

The model is a user model and we allow users to not have a timezone, in which case I want to show the default configured timezone.

```
best_in_place u, :time_zone, as: :select, url: admin_user_path(u), collection: ActiveSupport::TimeZone.zones_map.keys.select{|tz| tz.include?("US")}.map{|tz| [tz,tz]}, display_with: lambda{ |v| v ? v : "#{Rails.application.config.time_zone} (default)" }
```

Am I missing something obvious?

Thxs.

**Comment by seuros** [comment]
display_with is not thread safe.
It better to add this check in your model if possible.

**Comment by shyrahnama** [comment]
Perfect. Thanks for the quick reply!

**Comment by soberstadt** [comment]
Should this be closed then?

**Comment by shyrahnama** [comment]
Yep, it can be closed. Added an instance method to my model to return the default value and it works fine.

**Comment by coderawal** [comment]
@shyrahnama Can you show how you did that ? I'm too facing the same problem but unable to solve that. Hoping you will help.
