### ISSUE TITLE
Rails 4 - wrong url

### ISSUE THREAD

**Issue by olegsobchuk** [bernat/best_in_place#451]
Hi!
I'm using rails 4.2
When I use bip, I get wrong path (also if add url: ..., or path: ... attributes)
I get method put, to index.
example: edit User object, get users_path with method put
Can you help me?
Thx!

**Comment by seuros** [comment]
did you add jquery-ujs ?

**Comment by olegsobchuk** [comment]
../app/assets/javascripts/application.js.coffee
//= require jquery_ujs

**Comment by seuros** [comment]
can you provide a sample app with this bug ?

**Comment by olegsobchuk** [comment]
unfortunately this is private repo ((
maybe it does not work with rails 4?

**Comment by seuros** [comment]
I said to provide a same app, not the repo.

Create a new rails 4.2 app and reproduce the bug in it.

**Comment by olegsobchuk** [comment]
Oh, I see!
https://github.com/olegsobchuk/example_app
git@github.com:olegsobchuk/example_app.git

**Comment by chevinbrown** [comment]
What's the status here?? I'm having same issue, rails 4.2, ruby 2.2.1. the data attribute is "data-bip-url", but if I change that to "data-url", it works.

**Comment by olegsobchuk** [comment]
still open, I declined BIP and wrote edit in line via JS
BIP is broken for Rails 4

**Comment by chevinbrown** [comment]
Is there a Rails 4 branch we can use?

**Comment by duffyjp** [comment]
I use this fork:  
```ruby
gem 'best_in_place', github:'widernet/best_in_place', branch: 'rails-4'         
```
It works fine in 4.1.5... for what I need anyway.

**Comment by stereodenis** [comment]
@olegsobchuk where is best_in_place gem in your [Gemfile](https://github.com/olegsobchuk/example_app/blob/master/Gemfile)?

**Comment by stereodenis** [comment]
@duffyjp I want to help with improving this gem, so I need sample apps, that reproduced the issue

**Comment by olegsobchuk** [comment]
not works, can you investigating my problem?
https://github.com/olegsobchuk/example_app
User.create(name: 'Some name', email: 'my@e.mail')

**Comment by stereodenis** [comment]
@olegsobchuk I can, but you remove bip gem

**Comment by olegsobchuk** [comment]
@stereodenis sorry, fixed

**Comment by stereodenis** [comment]
@olegsobchuk https://github.com/olegsobchuk/example_app/pull/5

**Comment by olegsobchuk** [comment]
thanks, @stereodenis!!!
Result:
you have to use `gem 'best_in_place', github: 'bernat/best_in_place'`
