### ISSUE TITLE
Placeholder element class for style

### ISSUE THREAD

**Issue by soberstadt** [bernat/best_in_place#461]
It would be really great to be able to style the span tags based on if the span was built and contains the placeholder text or not. Maybe something like `bip-placeholder`.

My idea is to be able to style placeholders as grey text.

Would that be something you would be willing to add or accept a PR?

**Comment by stereodenis** [comment]
@soberstadt 
there is an option :place_holder
```
Options:
...
:place_holder: The nil param defines the content displayed in case no value is defined for that field. It can be something like "click me to edit". If not defined it will show "-".
```

**Comment by soberstadt** [comment]
Sorry, maybe I didn't make myself clear.

We are currently using the place_holder option to provide placeholder text. But what I would like to do is use css to give those using the placeholder text a different style. So I could do something like this:
![screen shot 2015-03-22 at 5 45 10 pm](https://cloud.githubusercontent.com/assets/1080613/6771888/8a939ff2-d0bb-11e4-8554-e02a9f8b7ce5.png)
 
My thought is that this css class could be added on the js side and then removed once it's updated through successful update.

Does that make better sense?

**Comment by stereodenis** [comment]
@soberstadt ok. I will take a look on it

**Comment by soberstadt** [comment]
Thanks!

**Comment by stereodenis** [comment]
@seuros need `feature` label
