### ISSUE TITLE
acts-as-taggable-on + best_in_place

### ISSUE THREAD

**Issue by sanjusoftware** [bernat/best_in_place#493]
This is an awesomely helpful gem without a doubt. I started using it and loved the way it just works. 

I have a small issue though, which is that I want to use it with a model that uses [acts-as-taggable-on](https://github.com/mbleigh/acts-as-taggable-on)

Any help with these 2 gems working together will be great. Essentially I want to be able to add tags with every hot on 'Enter'.. if not the fall back could be to just enter a comma separated tags list in a text field and then convert that to tags later in the controller, which doesn't look that elegant to me yet :)

**Comment by seuros** [comment]
Did you try to use the *_list  method?

**Comment by sanjusoftware** [comment]
not sure what do you mean... can you elaborate with an example?

**Comment by sanjusoftware** [comment]
alright thx @seuros 

I got this working by making use of the *_list method . duh, was simple enough and I was getting confused .. thx anyways
