### ISSUE TITLE
nested attributes

### ISSUE THREAD

**Issue by aribeiro** [bernat/best_in_place#51]
Hey it is possible use that with nested attributes, I try:

``` ruby
best_in_place @profile.user, :name
```

and 

``` ruby
best_in_place @profile, "user_attributes[name]"
```

But have no success

**Comment by betesh** [comment]
Since this ticket is linked from StackOverflow, it's worth adding the following update, even if this ticket is way out of date.

There is a pretty simple way to do this.  No need for any additional controllers.  You need to pass a `param` param to best_in_place.

    class Car < AR::Base
      has_one :wheel
      accepts_nested_attributes_for :wheel
    end

    best_in_place car.wheel, :last_rotation, path => car_path(car.id), type: :input, param: "car[wheel_attributes][id]=#{car.wheel.id}&car[wheel_attributes]"

**Comment by rruiz858** [comment]
Hey @betesh, I am currently trying to do this same exact procedure but I am not getting a successful time with what you added. 

```
class Cart << AR::Base
 has many LineItems
end

class LineItems <<AR::Base
 belongs_to Cart
 has_one :control 
 accepts_nested_attributes_for :control 
end

class Control<<AR::Base
belongs_to LineItems
end
```

I am showing a cart in the cart's show view. Within the cart's  show view, I have the ability to add lineItems. When an LineItem is created, a new control record is also created with a lineItem id and then it's shown in the cart.

```
@cart.lineitems.each do |line_items|
    <td> line_item.price</td>
    <td>line_item.name </td>
    <td>line_item.control.name</td>  *********
end
```

I want to be able to edit the line_item.control.name within the html table which is on the cart show view using best_in_place but I am not having any luck.. Any help would be AMAZING! =]

**Comment by betesh** [comment]
I answered on StackOverflow

**Comment by zenzei** [comment]
@Hi betesh, your solution is great! But it seems doesn't in version >  3.1 because there was a change in how the parameters are set in the requestData function.

Looking at the code I manage to get it working setting the new option 'bip-extra-payload' like this

```
best_in_place car.wheel, :last_rotation, 
  url: url_path(car), type: :input, 
  param: "car[wheel_attributes]",
  data: {'bip-extra-payload' => {wheel_attributes: {id: car.wheel.id}}},
```
 
Is just a hack as I understand that option is internal but it fix the issue I was having.

But the solution will not work if the record is a "new_record", because the bip-extra-payload is overwritten, in the helper.rb. 
```
      if real_object.respond_to?(:new_record?) and real_object.new_record?
        options[:data]['bip-new-object'] = true
        # collect name => value map of unsaved attributes to be serialized
        options[:data]['bip-extra-payload'] = Hash[real_object.changes.map { |k,v| [k, v[1]] }]
      end
```

An ugly solution could be replacing that line with a merge
```
        options[:data]['bip-extra-payload'] = Hash[real_object.changes.map { |k,v| [k, v[1]] }].merge(options[:data]['bip-extra-payload'] || {})
```
