### ISSUE TITLE
How to add datetimepicker

### ISSUE THREAD

**Issue by whodabudda** [bernat/best_in_place#522]
I need the time component in a popup calendar for a datetime input field.  Been working with http://xdsoft.net/jqplugins/datetimepicker/ ,  and can get it to show as follows:
<td><%= best_in_place item,:occur_dttm, :as => :input, :class => :default_datetimepicker %></td>
But I can't get the value from the widget into the input field when using best_in_place.   Any suggestions?

**Comment by arif-trackmy** [comment]
Any progress on this issue ? Did someone get it working?

**Comment by cd-rum** [comment]
@whodabudda Why that particular picker, by the way?

**Comment by whodabudda** [comment]
Hi all,  I actually did get it to work, albeit without best_in_place.   It was over a year ago and I don't remember the details.  I didn't even know I had a reply here until I revisited github for another project.  If you want to know, I'll dig it out from the old project.  for cd-rum:  I chose this picker because I liked the looks of it, and it seemed like it would be easy to use.
