### ISSUE TITLE
Confirm checkbox alert

### ISSUE THREAD

**Issue by mario-amazing** [bernat/best_in_place#573]
How can I display confirmation alert before change checkbox value?
 best_in_place item, :received, as: :checkbox, confirm: "Are u sure?",collection: { false: "N", true: "Y"}

**Comment by victorhazbun** [comment]
Is this gem working on Rails 5?

**Comment by megosparta** [comment]
yeap

**Comment by vypah** [comment]
@megosparta any luck with this ?

**Comment by megosparta** [comment]
@vypah only hidden button help

**Comment by vypah** [comment]
@megosparta yea I guess this is kinda broken. I also switched to a simple `button_to` instead of using `bip`
