### ISSUE TITLE
line breaks in textareas

### ISSUE THREAD

**Issue by brianmaissy** [bernat/best_in_place#62]
This is a feature request.

When using a textarea, the developer often intends for the field to contain line breaks. Best_in_place doesn't display newlines in textareas as html `<br>` tags. It would be really convenient if it did by default, or had an option to.

I was able to implement a workaround with a display_as, but there are two problems with it:
1) During the time between sending the ajax request and receiving the response, it temporarily is displayed without the breaks, and then switches over. This is a little ugly.
2) It's a rather complicated workaround for a really common task.

Let me know if this is already possible and I just missed it.

**Comment by Akshg** [comment]
I am using display_with: :simple_format. Its working fine. But then, the text does not remain editable at all.
I tried fetching directly from git repo, but it doesn't help. Any input will be helpful.
Thanks.

**Comment by cg5544** [comment]
@Akshg I am running into the sample issue. `:simple_format` works but text is not editable anymore.

**Comment by Akshg** [comment]
@cg5544 Even i was am facing the same issue at that time. Any progress?
