### ISSUE TITLE
Release a new version, please

### ISSUE THREAD

**Issue by diesl** [bernat/best_in_place#636]
The title says it all: Please release a new version. The last version is from 2017 (!)

@seuros: 
You merged last pull request #631 and you also released last version 3.1.1. Can you please help here?

**Comment by mmotherwell** [comment]
Just put this in your gemfile:

gem "best_in_place", git: "https://github.com/bernat/best_in_place"

**Comment by sk-** [comment]
Actually it would be much better to have a release, as the suggestion above required having got installed in the system which is not always true, for example when building docker images.

@seuros @bernat would it be possible to release a new version?
